### ISSUE TITLE
Set up / Clean up your other social media profiles

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-Berelarsenp#17]
It's good to make yourself reachable in other platforms. You can come choose any platform and this is entirely up to you. A few recommendations from our part:
* Twitter
* Facebook
* angel.co
* medium.com
* StackOverflow

**Deliverable:** Once you're done. Post your profiles in this issue and close it for review.

`RMOTR: PB#6`

**Comment by Berelarsenp** [comment]
https://stackoverflow.com/users/9797057/berelarsenp
https://twitter.com/berelarsenp
https://medium.com/@berelarsenp (don't have anything here yet. Will post the blog posts ideas here.)
