### ISSUE TITLE
Clean up your LinkedIn profile

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-Berelarsenp#19]
Key points:
- Good portfolio picture
- Detailed employment information (sell yourself on how you made a difference at your workplaces)
- References
- Connections with people in relevant fields, old co-workers
- Make sure you include your other social profiles and links
- Validate that your profile is publicly visible
- Include RMOTR's course in your Education section

Follow this guide for advice:
https://www.themuse.com/advice/the-31-best-linkedin-profile-tips-for-job-seekers

**Deliverable:** Once you're done. Post your LinkedIn public URL in this issue and close it for review.

`RMOTR: PB#2`

**Comment by Berelarsenp** [comment]
https://www.linkedin.com/in/berelarsenp/

**Comment by jasonmeeks** [comment]
Looks good! 

For your summary, there are some errors with your english. If you will be applying to spanish jobs, perhaps make your profile in spanish? Otherwise, you'll need to have someone edit your current summary.  I'm not sure on whether it is better to have linkedin in spanish or english.
