### ISSUE TITLE
Research other sites with offers

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-Berelarsenp#2]
This is an exploratory phase as you're creating your resume, updating your profiles and building your public personal brand.

Come up with other websites that you might find interesting to apply for jobs and investigate them. Examples are:
* [LinkedIn jobs](https://www.linkedin.com/jobs)
* [The Muse](https://www.themuse.com/)
* [Indeed](https://www.indeed.com)
* [Glassdoor](https://www.glassdoor.com)
* [Angel List](https://angel.co/jobs)
* [Remote.co](https://remote.co)
* [We Work Remotely](https://weworkremotely.com)
* [Remote OK](https://remoteok.io/)

There are [many](https://skillcrush.com/2015/07/14/job-sites-to-find-your-first-developer-job/) more. If you come up with new ones, please post them here so other students can benefit from it too.

**Deliverable:** Compile a list of the sites that you'd like to use and post them as a comment here. Put notes to know if you've created an account/profile already or it's just in your list.

`RMOTR: JS#4`

**Comment by Berelarsenp** [comment]
Linkedin Jobs (have an account)
https://www.upwork.com/ (it's for freelance work, but I'd like to give it a try)
https://ar.indeed.com/?r=us
https://www.workana.com/
