### ISSUE TITLE
 Submit a document for your project's scope

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-Berelarsenp#6]
From the spec:
We’re going to evaluate how well your estimations work. That’s why we need you to tell us the scope beforehand. You need to include a document (that will be shared with the jury) specifying what your app will and will not do.

You’re free to format the document as you wish and to add whatever info you consider necessary; but there are some things that you have to include:

Project Name. Choose a name for your project.
Team members. Name, short bio, github profile, [social media profile] (optional).
Team captain (if group). Select one of the participants so we can have a direct communication with her/him.
Short description of your project. What’s going to do? What problem is it going to solve?
Detailed list of the features the project will support at Demo Day.
API’s you’re going to use
Technical details: technologies used, frameworks, deploy method, hosting, etc.

**Deliverable**: Once you're done, post your scope document in this issue and close it for review.

`RMOTR: DD#4`

**Comment by Berelarsenp** [comment]
https://docs.google.com/document/d/1nQk_BNBJKBsFCjkj2lAAvcHTpsoK6mz7o4JlxitcMnY/edit?usp=sharing
