### ISSUE TITLE
Review Demo Day Specs and Form Teams

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-Berelarsenp#8]
Read the spec to make sure you are clear on the project requirements:
https://docs.google.com/document/d/1K3uZBOLgJ-RPLzO0QCKStzdfbNAtagLSodamaV8-wlk/edit?usp=sharing

**Deliverable**: Decide if you will work alone or as a team for Demo Day. After you have read over and discussed the spec with your group, post your group members as a comment and close the issue.

`RMOTR: DD#1`

**Comment by Berelarsenp** [comment]
**Team members**
Berenice Larsen Pereyra    __team_captain__
Jordan Winfery
